openapi: 3.1.0
info:
  version: 1.0.0
  title: University
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of University
tags:
  # теги, що ви будете використовувати
servers:
  - url: http://127.0/0.1:3000
  - url: #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
